name: Lighthouse
on: push
jobs:
    static-dist-dir:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run Lighthouse against a static src dir
              uses: treosh/lighthouse-ci-action@v11
              with:
                  configPath: "./lighthouserc.json"
